SELECT bo.AUTHOR_ID, au.AUTHOR_NAME, bo.CATEGORY, SUM(bo.PRICE * bs.SALES) AS 'TOTAL_SALES' 
FROM BOOK AS bo JOIN AUTHOR AS au ON bo.AUTHOR_ID = au.AUTHOR_ID 
    JOIN BOOK_SALES AS bs ON bo.BOOK_ID = bs.BOOK_ID
WHERE 
    MONTH(bs.SALES_DATE) = 1 
    AND YEAR(bs.SALES_DATE) = 2022
GROUP BY au.AUTHOR_ID, bo.CATEGORY 
ORDER BY au.AUTHOR_ID, bo.CATEGORY DESC